Mqtt chatroom
mtjon/introduction-to-dsh pull request #7
Opened 2019-09-02 12:18 UTC by vomov

2019-09-02 13:29 UTC, mtjon requested changes
Please make sure naming in the cheatsheet is generic and does not refer to a single trainer (marco in this case).
Please change back the variable substitution within double quotes (`"`) as referenced in the Bash Manual.

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +nano pom.xml
This is unacceptable.

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +<version>1.0.1-SNAPSHOT-MARCO</version>
might want to choose a more generic name

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +<version>1.0.1-SNAPSHOT-MARCO</version>
on second thought... the name doesn't get more generic than this.

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +  dataserviceshub-docker-$TENANT.jfrog.io/tenant-example:1.0.1-SNAPSHOT-MARCO
see earlier comment on generic naming

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +  $jfrog_url/tenant-example:1.0.1-SNAPSHOT-MARCO
generic naming consistency

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +  "image": "dataserviceshub-docker-training.jfrog.io/tenant-example:1.0.1-SNAPSHOT-MARCO",
generic naming

2019-09-02 13:29 UTC, mtjon commented on cheatsheet.md
> +## marco snapshot
generic naming.

2019-09-02 13:29 UTC, mtjon commented on mqtt.md
> +"https://api."$PLATFORM".kpn-dsh.com/datastreams/v0/mqtt/token" \
These extra quotes are unncessary, see: http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Single-Quotes

2019-09-02 14:04 UTC, vomov commented on mqtt.md
> +"https://api."$PLATFORM".kpn-dsh.com/datastreams/v0/mqtt/token" \
Fixed

2019-09-02 14:10 UTC, vomov commented on cheatsheet.md
> +## marco snapshot
Fixed

2019-09-02 14:10 UTC, vomov commented on cheatsheet.md
> +  "image": "dataserviceshub-docker-training.jfrog.io/tenant-example:1.0.1-SNAPSHOT-MARCO",
Fixed

2019-09-02 14:10 UTC, vomov commented on cheatsheet.md
> +  $jfrog_url/tenant-example:1.0.1-SNAPSHOT-MARCO
Fixed

2019-09-02 14:10 UTC, vomov commented on cheatsheet.md
> +  dataserviceshub-docker-$TENANT.jfrog.io/tenant-example:1.0.1-SNAPSHOT-MARCO
Fixed

2019-09-02 14:10 UTC, vomov commented on cheatsheet.md
> +<version>1.0.1-SNAPSHOT-MARCO</version>
Managed to make more generic by removing the name

2019-09-02 14:15 UTC, vomov commented on cheatsheet.md
> +nano pom.xml
added Vim

2019-09-10 08:03 UTC, mtjon requested changes

2019-09-10 08:03 UTC, mtjon commented on cheatsheet.md
> +nano pom.xml
;)

2019-09-10 08:03 UTC, mtjon commented on mqtt.md
> +-d '{"id":"'$THING_ID'"}' > mqtt-token_1.txt
Isn't this too much of a hint? Let them struggle.

2019-09-10 10:33 UTC, mtjon approved these changes
LGTM

2019-09-10 10:33 UTC, merged